#include "subsystems/ShooterSystem.h"
#include <frc/smartdashboard/SmartDashboard.h>
#include <frc/XboxController.h>
#include <rev/SparkFlex.h>
#include "frc/Timer.h"
#include <rev/config/SparkFlexConfig.h>
#include <frc2/command/Commands.h>

ShooterSystem::ShooterSystem(){
    SetName("ShooterSystem");
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SetSubsystem("ShooterSystem");
  rev::spark::SparkFlexConfig globalConfig;
  rev::spark::SparkFlexConfig LeftMSrConfig;
  rev::spark::SparkFlexConfig RightMSConfig;
  rev::spark::SparkFlexConfig BottomLeftMSConfig;
  rev::spark::SparkFlexConfig ConveyorConfig;
  

  LeftMSrConfig.Apply(globalConfig);
  RightMSConfig.Apply(globalConfig);
  BottomLeftMSConfig.Apply(globalConfig);
  ConveyorConfig.Apply(globalConfig);

  ;m_leftMS.Configure(LeftMSrConfig,
                         rev::ResetMode::kResetSafeParameters,
                         rev::PersistMode::kPersistParameters);
  m_rightMS.Configure(RightMSConfig,
                           rev::ResetMode::kResetSafeParameters,
                           rev::PersistMode::kPersistParameters);
 m_BottomLeftMS.Configure(BottomLeftMSConfig,
                          rev::ResetMode::kResetSafeParameters,
                          rev::PersistMode::kPersistParameters);
m_Conveyor.Configure(ConveyorConfig,
                          rev::ResetMode::kResetSafeParameters,
                          rev::PersistMode::kPersistParameters);
 
/*
 AddChild("motor", &m_motor);
 m_motor.SetInverted(false);
 */


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}

// void ShooterSystem::Periodic() {
//     // Put code here to be run every loop

// }

// void ShooterSystem::SimulationPeriodic() {
//     // This method will be called once per scheduler run when in simulation

// }

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


// Put methods for controlling this subsystem
// here. Call these from Commands.


void ShooterSystem::ShooterSpeed1() {
   m_rightMS.Set(0.8);
    m_Conveyor.Set(0.1);
    m_leftMS.Set(-0.8);
    m_BottomLeftMS.Set(0.8);
    
}
 void ShooterSystem::ShooterSpeed2(){
    m_rightMS.Set(0.55);
    m_Conveyor.Set(0.1);
    m_leftMS.Set(-0.55);
    m_BottomLeftMS.Set(0.8);
 }
 void ShooterSystem::AutoShoot(){
   m_timer.Reset();
        m_timer.Start();
  if (m_timer.Get() <= 5.0_s){
    m_rightMS.Set(0.55);
    m_Conveyor.Set(0.1);
    m_leftMS.Set(-0.55);
    m_BottomLeftMS.Set(0.8);
  }

 }
 void ShooterSystem::ShooterIn(){
 m_BottomLeftMS.Set(0.8);
 }
 
 void ShooterSystem::ShooterOut(){
 m_BottomLeftMS.Set(-0.3);
  }
 
  void ShooterSystem::ShooterStop1(){
    m_rightMS.Set(0);
    m_Conveyor.Set(0);
    m_leftMS.Set(0);
  }
 
 
  void ShooterSystem::ShooterStop2(){
m_BottomLeftMS.Set(0);
 }
